In [1]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats


# Question 1

In [2]:
cutlet=pd.read_csv("C:\\Users\\HP\\Desktop\\ExcelR\\Assignment\\Ass 3 Hypothesis testing\\Cutlets.csv")

In [3]:
cutlet.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [4]:
array=cutlet.values
UnitA = array[:,0]
UnitB = array[:,1]

In [5]:
stats.ttest_ind(UnitA,UnitB)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [6]:
#As obtained 'p' value is 0.974 grerater than given alpha that is significance value,Accept null hypothesis

# Question 2

In [7]:
TAT=pd.read_csv("C:\\Users\\HP\\Desktop\\ExcelR\\Assignment\\Ass 3 Hypothesis testing\\LabTAT.csv")
TAT

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [8]:
p_value=stats.f_oneway(TAT.iloc[:,0],TAT.iloc[:,1],TAT.iloc[:,2],TAT.iloc[:,3])

In [9]:
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [10]:
#As obtained 'p' value is 0.974 grerater than given alpha that is significance value,Accept null hypothesis

# Question 3 

In [11]:
BR=pd.read_csv("C:\\Users\\HP\\Desktop\\ExcelR\\Assignment\\Ass 3 Hypothesis testing\\BuyerRatio.csv")

In [12]:
BR

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [13]:
BR.describe()

East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [14]:
objList = BR.select_dtypes(include = "object").columns
print (objList)

Index(['Observed Values'], dtype='object')


In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
for feat in objList:
    BR[feat]=le.fit_transform(BR[feat].astype(str))
    
print(BR.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observed Values  2 non-null      int32
 1   East             2 non-null      int64
 2   West             2 non-null      int64
 3   North            2 non-null      int64
 4   South            2 non-null      int64
dtypes: int32(1), int64(4)
memory usage: 200.0 bytes
None


In [18]:
import scipy.stats as stats
stats.f_oneway(BR.iloc[:,0],BR.iloc[:,1],BR.iloc[:,2],BR.iloc[:,3],BR.iloc[:,4])

F_onewayResult(statistic=0.5960896991149738, pvalue=0.6818002355762813)

In [19]:
BR1 = BR.iloc[:,1:]

In [20]:
BR1

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [21]:
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(BR1)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 1.595945538661058.
p value is 0.6603094907091882.
df is 3.
Expected table is 
[[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


# Question 4

In [22]:
COF=pd.read_csv("C:\\Users\\HP\\Desktop\\ExcelR\Assignment\\Ass 3 Hypothesis testing\\Costomer+OrderForm.csv")

In [23]:
COF.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in COF.columns:
    COF.loc[:,feat]=le.fit_transform(COF.loc[:,feat])

In [25]:
COF.head()

Phillippines  Indonesia  Malta  India
0             1          1      0      1
1             1          1      1      0
2             1          0      0      1
3             1          1      1      1
4             1          1      0      1

In [26]:
stats.f_oneway(COF.iloc[:,0],COF.iloc[:,1],COF.iloc[:,2],COF.iloc[:,3])

F_onewayResult(statistic=1.286168556089167, pvalue=0.2776780955705948)

In [27]:
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(COF)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 112.74730231885849.
p value is 1.0.
df is 897.
Expected table is 
[[0.74793008 0.73689052 0.7424103  0.77276909]
 [0.74793008 0.73689052 0.7424103  0.77276909]
 [0.49862006 0.49126035 0.4949402  0.51517939]
 ...
 [0.74793008 0.73689052 0.7424103  0.77276909]
 [0.99724011 0.9825207  0.9898804  1.03035879]
 [0.49862006 0.49126035 0.4949402  0.51517939]]
